id = "clarity"
name = "Clarity"
version = "0.0.1"
schema_version = 1
authors = ["Hugo <hugo@hiro.so>"]
description = "Clarity language support"
repository = "https://github.com/hirosystems/clarity-zed"

[language_servers.clarity-lsp]
name = "Clarity Language Server"
language = "Clarity"

[grammars.clarity]
repository = "https://github.com/xlittlerag/tree-sitter-clarity"
commit = "cbb3ffe8688aca558286fd45ed46857a1f3207bb"
